- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Ensure Apache is running and enabled on boot
  systemd:
    name: apache2 
    state: started
    enabled: true

- name: Copy Apache virtual host configuration
  copy:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache



       