---
- name: Install MySQL Server and Python bindings
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
  become: true
  tags: mysql

# Minimal working wait for MySQL (no changes to your structure)
- name: Wait briefly for MySQL initialization
  ansible.builtin.pause:
    seconds: 15
  tags: mysql

- name: Ensure MySQL is running and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
  become: true
  tags: mysql

- name: Debug mysql_root_password
  ansible.builtin.debug:
    msg: "{{ mysql_root_password }}"
  tags: mysql

# In your existing password task, replace ONLY these lines:
- name: Change MySQL root authentication
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    plugin: mysql_native_password
    # Replace check_implicit_admin with this:
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true
  tags: mysql