    - name: Install PHP and modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Copy PHP index page
      template:
        src: index.php.j2
        dest: /var/www/html/index.php
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Restart Apache